### ISSUE TITLE
Duda 

### ISSUE THREAD

**Issue by VictorVmg** [USB-EC3081-III-2019/EC3081-G02#11]
Buenas noches profesor. Una pregunta, en nuestro caso somos el grumo Nro.2 y para el proyecto debemos trabajar con un relé y un Servomotor. Sin embargo, quisiera saber si el servomotor con el que vamos a trabajar será limitado por angulo de giro hasta 180 grados (creo que le dicen motor de paso) o con servomotor con posibilidad de giro de 360grados.

**Comment by ncertad** [comment]
Ambos son servomotores (sean de medio giro o giro completo). Lo que deben hacer es averiguar como se produce una señal PWM con el PIC ya que esa es la forma de controlar el giro del servomotor. Por ejemplo para sevomotores de marca HITEC:
 > Pulse duration is from 0.9ms to 2.1ms with 1.5ms as center. The pulse refreshes at 50Hz (20ms).
