### ISSUE TITLE
duda

### ISSUE THREAD

**Issue by VictorVmg** [USB-EC3081-III-2019/EC3081-G02#12]
Buenas noches profesor, tengo una duda respecto a nuestro proyecto. Habiamos dicho que seria un control de irradiación y que iba a contar con:

1. Relé
2. Servomotor como actuador. Segun lo que hemos investigado, este será controlado con una de las dos posibles salidas CCP del PIC. 

La duda está en el relé, osea, ¿el mismo controlaría la luminaria del invernadero haciendo una especie de interruptor crepuscular?

**Comment by ncertad** [comment]
con el servomotor pueden "simular" que están moviendo el cobertor externo del invernadero para evitar la entrada de luz. Ejemplo:
* Servomotor en 0 grados: Cobertor abierto.
* Servomotor en 90 grados: Cobertor semi-cerrado.
* Servomotor en 180 grados: Cobertor completamente cerrado.

Por otro lado, con el relé pueden controlar el encendido de la iluminación artificial
