### ISSUE TITLE
write

### ISSUE THREAD

**Issue by GEnma29** [USB-EC3081-III-2019/EC3081-G02#5]
![escribir](https://user-images.githubusercontent.com/53823068/65629603-a146a100-dfa1-11e9-8b60-ce76c3d261f8.png)

**Comment by ncertad** [comment]
Hola, no se porque todas las imagenes que subieron aparecen como "issues" en su repositorio. TOdas las dudas las pueden plantear por esta vía sin necesidad de enviarme un correo. Para ello plantean el problema o la duda y me etiquetan en la descrpción (@ncertad ).


La forma correcta de colocar código en C en la documentación es usando el código Markdown correspondiente, sin necesidad de adjuntar un printscreen:
```c
void LCD_Escribir(char dato){

}
```

En este [enlace](https://guides.github.com/features/mastering-markdown/) tienen una guía sobre como formatear texto en los archivos .md y las wikis de github.
